CREATE TABLE usuarios (
    ID_USUARIO CHAR(4) PRIMARY KEY NOT NULL,
    USERNAME VARCHAR(20) NOT NULL UNIQUE,
    CONTRASENA VARCHAR(100) NOT NULL,
    ROL VARCHAR(15) NOT NULL);
CREATE TABLE cliente (
    ID_CLIENTE CHAR(4) PRIMARY KEY NOT NULL,
    NOMBRE VARCHAR(50) NOT NULL,    
    APELLIDO VARCHAR(50) NOT NULL,  
    EMAIL VARCHAR(100) NOT NULL UNIQUE,
    CITY VARCHAR(50));
CREATE TABLE ventas (
    ID_VENTAS CHAR(4) PRIMARY KEY NOT NULL,
    VALOR DECIMAL(10,2) NOT NULL,   
    FECHA DATE NOT NULL,           
    ID_CLIENTE CHAR(4) NOT NULL,
    ID_USUARIO CHAR(4) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES cliente(ID_CLIENTE),
    FOREIGN KEY (ID_USUARIO) REFERENCES usuarios(ID_USUARIO));